### ISSUE TITLE
Test Interstitials

### ISSUE THREAD

**Issue by iWareDesigns** [mobfox/MobFox-iOS-SDK#38]
Hi,

We are using AdMob as our mediation platform and have come across a couple of issues on our iPad Air 2 with iOS 10.3.1 (We have not tested any other devices or iOS versions yet).

1. Could you confirm what version of the AdMob SDK we should be using, we currently have 7.19.1

2. We have implemented MobFox into AdMob's mediation and the test banner adverts display, but they don't always animate?  Is this correct?  Should they permanently animate?

![apple_testbannerad](https://cloud.githubusercontent.com/assets/28161411/25696064/a953b3a6-30ad-11e7-8a47-ccb578fa312f.png)

3. We seem to have a problem with the test interstitial not displaying after we have task switched.  If we do not task switch the test interstitial's behave correctly.

  a) Request interstitial and it loads okay.
  b) Before displaying the interstitial we press the home button to return to the iOS desktop.
  c) We then switch back to our App by tapping on its icon.
  d) We then attempt to show the interstitial and nothing appears.  The isReady method is returning TRUE.

Both the AdMob delegates "interstitialWillPresentScreen" and "interstitialDidFailToPresentScreen" are not called when the interstitial is not displayed even though it has loaded and is ready.  Again, this only seems to happen when task switching.

Regards,

iWare Designs Ltd.

**Comment by nabriski** [comment]
Hi,

We'll take a look at these and update this issue when we have a resolution.

Thanks

**Comment by iWareDesigns** [comment]
Hi,

Thanks for the update.  We have just added Unity Ads, and their interstitial adverts work okay.  It seems to be MobFox only,  AdMob, Facebook, Smaato and Unity Ads all display after switching back to the iOS home screen and back to the App.

Regards,

iWare Designs Ltd.

**Comment by shimisheetrit** [comment]
Hi,

I'll answer for each issue you mention separately: 

1.  AdMob Ads SDK latest version 7.20.0 works with our lib.
2. ad animation shouldn't be always permanent, and it depends on a specific GIF. in that case it's fine the animation should stop in some level.
3. Now after implementing some changes, **it's fixed in latest version v3.1.6f** and app could loading interstitial ad right after lounging the app (as example in viewDidLoad of the ViewController), then pressing the home screen or switching to other app, after returning interstitial ad could be displayed (with MobFox show function).
The delegate functions "interstitialWillPresentScreen" and "interstitialDidFailToPresentScreen" will be invoked before presenting ad and after failure (for example when no ad return) respectively. 
On any case one of the delegate function not being called, please update us and we'll solve it immediately.

**Comment by nabriski** [comment]
Just to clarify, the animated gif in our test hash stops animating after a few cycles. That's just the way it was made.

**Comment by iWareDesigns** [comment]
Hi,

I have just been testing interstitial adverts using the new SDK and noticed something that I am not sure about.

We load the interstitial and receive the "interstitialDidReceieveAd" event.

At this point we have not displayed the interstitial.

When we press the iPad's "Home" button we receive the "interstitialWillDismissScreen" and the "interstitialDidDismissScreen" events (Even though the interstitial is not visible).  According to Google's documentation these two events should be called when the interstitial is to be animated off screen and has animated off screen.

I have just done the same test with AdMob's test adverts and when pressing the "Home" button we do not receive the "interstitialWillDismissScreen" or the "intersititalDidDismissScreen".  These two events should only be received when a visible interstitial is physically closed and the interstitial disappears returning control back to the App.

Regards,

iWare Designs Ltd.
